### ISSUE TITLE
Request: Allow modders to specify the order of settings in the UI

### ISSUE THREAD

**Issue by paperpancake** [chadvandy/mod_configuration_tool#1]
The settings are currently ~~randomly ordered in the UI~~ alphanumerically sorted by option key. Could we provide a way to allow modders to specify the order? It could be as straightforward as having the order of the UI be the same as the order in which they are added in mct/settings/?.lua

**Comment by paperpancake** [comment]
If you wanted to keep it flexible, a possible implementation might be to allow the user to set a sorting function and provide a couple of default options with built-in support.

Some a rough draft psuedo-code for illustration.

    --The modder using MCT could call something like this

    section1:set_option_sort_function("index_sort")
    section2:set_option_sort_function("key_sort")
    section3:set_option_sort_function(
        function(section_key)
            --the returns a list of options in their own customized order
        end
    )

    ----------------------------------------------------------------
    --And MCT would have functions like

    function section_obj:set_option_sort_function(sort_function)
        if sort_function == "index_sort" then
            self.sort_function = self.index_sort_function --sort based on the order the options were added to the mod_obj
        elseif sort_function == "key_sort" then
            self.sort_function = self.key_sort_function --sort alphanumerically by key
        elseif is_function(sort_function) then
            self.sort_function = sort_function
        else
            --error: bad argument
        end
    end

    function section_obj.index_sort_function(section_key)
        --return a list sorted by the order the items were added
    end

    function section_obj.key_sort_function(section_key)
        --do the stuff here you are already doing to get table.sort(ordered_option_keys)
        return ordered_option_keys
    end

    ----------------------------------------------------------------

    function mod_obj:set_option_sort_function(...)
        --for each section
            current_section:set_option_sort_function(...)
    end

    function mct_mod:set_positions_for_options()
        --very similar to how it's already written, but 
        --instead of what you currently have for creating and sorting ordered_option_keys,
        --you would call the section's sort function
        local current_section = self:get_section_by_key(section_key)
        current_section.sort_function(section_key)
    end

**Comment by chadvandy** [comment]
incorporated
