### ISSUE TITLE
find out why popups sometimes don't work at all

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/mod_configuration_tool#139]

**Comment by paperpancake** [comment]
I'm not sure if this covers every case, but here's a use case that's consistently reproducible:

1. Have some existing finalized settings in MCT for some mods before starting the game. (If needed, start the game with a mod, finalize a setting, and exit.)
2. Enable a new mod with MCT settings that you haven't used before. Start the game and get to the frontend main menu.
3. Open MCT settings.
4. Without finalizing, change a setting and then try to close the MCT panel.
5. Nothing will happen (a bug). It should show a pop-up warning that you have unsaved changes.

**Comment by chadvandy** [comment]
Thanks paper!!
