### ISSUE TITLE
The "Finalize Settings Pop-up" doesn't account for the same option_key used in more than one mod

### ISSUE THREAD

**Issue by paperpancake** [chadvandy/mod_configuration_tool#145]
If two different mods use the same option key for one of their options, and if the user changes both of them, the "Finalize Settings Pop-up" doesn't display them both.

For example, the mods "Find Idle Units" and "Attack Move and Counter Charge" both have an `option_which_config`. If you change that for both of them (even if you change them to different settings), only one will appear in the pop-up when you click "Finalize All Mods". (See the attached screenshot.)

![image](https://user-images.githubusercontent.com/56833110/91382310-556a3080-e7de-11ea-920d-e70f4bb3b50d.png)

**Comment by chadvandy** [comment]
Good catch!
