### ISSUE TITLE
fix tab states

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/mod_configuration_tool#32]
when tab A is selected, deselected tab B, etc

**Comment by paperpancake** [comment]
The description is vague enough that I can't tell if this comment explains this further or belongs in its own issue:

Let's say that mod A and mod B are both using MCT. The user checks a checkbox in mod A's settings, then the user switches to mod B's tab without pressing finalize before leaving mod A.
- If they press finalize while looking at mod B, and then they go back to mod A, their change to mod A's settings will be saved (which is what I'd expect if they didn't get a warning when leaving mod A).
- However, if they do not press finalize, and they go back to mod A's tab to look at their settings, their changes will revert to what they had before (which is not what I'd expect).
