### ISSUE TITLE
A mod's settings revert to the default if temporarily removed from the mod list 

### ISSUE THREAD

**Issue by paperpancake** [chadvandy/mod_configuration_tool#51]
To reproduce (I'm using CA's mod launcher - sacrilege, I know. I suspect this happens with KMM, too, though I haven't verified):

1. Enable Mod A and Mod B (both mods need an MCT setting)
2. Start the game, open MCT, change some settings in Mod A, finalize
3. Exit the game
4. Disable Mod A
5. Start the game, then exit the game (you don't need to do anything else, not even open the MCT panel while in the game this time, though you can if you want)
6. Enable Mod A again
7. Start the game and check the settings for Mod A. They will have reverted back to the default

There is an advantage to MCT's forgetfulness: you won't get bloat in your file that saves these settings.
However, I personally think the inconvenience to the end user outweighs that advantage. As an end user, I personally would rather have it keep track of all of my non-default settings, even with the bloat, as long as it wasn't more than a few MB.

What would be ideal, I think, would be to save everything by default and then have a "Delete Settings for Unused Mods" button on the MCT settings page that would delete everything except currently installed mods or mods that have been used in the last X number of days or something. Or you could have a list of mods the user could scroll through and delete each manually, though that's probably overkill.

**Comment by paperpancake** [comment]
This issue is an important one for me. When I'm testing, I'll frequently disable some mods temporarily. And most modders will tell our users to troubleshoot problems by disabling mods to narrow down where the problem is. I'd hate to have my settings reset every time I did that.

**Comment by paperpancake** [comment]
I've been thinking about this some more, I think my ideal solution would:

1. Have a checkbox on the MCT settings page for "Display Inactive Mods"
2. If the checkbox was checked, the list of current mods on the left part of MCT would at the end of that list also show mods that aren't currently enabled but for which MCT has saved settings. Ideally, those mods would be greyed out or be otherwise visually distinct. (It doesn't need to display what those settings when clicked on, since we won't have access to the mct/settings/?.lua file for that mod, or if you wanted it could just show them as text.)
3. The list of current mods on the left part of MCT would have a "trash" button for deleting them individually.
4. Also have a "Delete Settings for Unused Mods" button on the MCT settings page for faster cleanup. That would delete everything except currently installed mods or mods that have been used in the last X number of days or something.

**Comment by chadvandy** [comment]
Foundationally, this works; stuff is cached when disabled. Improvements are tracked in #62
