### ISSUE TITLE
Enable dummy options

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/mod_configuration_tool#56]
Integrate options that aren't tracked for Finalize Settings/mct_settings.lua.

Useful for UI-only options.

Alternatively - develop more UI control and keep all options as fully integrated

**Comment by paperpancake** [comment]
I'm looking forward to having a way to put just two options on some rows instead of three. I'm making a set of options that come in sets of two. I'm hoping I can either use invisible dummy options or make use of the "more UI control" you mention.
