### ISSUE TITLE
ui_select_value doesn't update the UI for checkboxes

### ISSUE THREAD

**Issue by paperpancake** [chadvandy/mod_configuration_tool#69]
I created this issue based on the live Steam version. Is this a duplicate of #57? That issue is marked as closed, so you might have fixed this and just not committed the code yet (or it's possible that I just can't find the fix here on GitHub).

**Comment by chadvandy** [comment]
I have a second branch open, active_dev. Keeping master for the current retail branch, to keep everything clean
